### ISSUE TITLE
TypeScript + Webpack minification error

### ISSUE THREAD

**Issue by tatumio** [Bitcoin-com/bitbox-sdk#158]
When using TypeScript and Webpack, production minification causes types in typeforce to not working correctly, e.g. ECPair. It should be replaced with object destructing to avoid such bugs.

```
ERROR	{ Error: Expected property "0" of type ECPair, got y
    at a (/var/task/app.js:49:44821)
    at tfSubError (/var/task/app.js:49:45999)
    at /var/task/app.js:16:6841
    at Array.every (<anonymous>)
    at t (/var/task/app.js:16:6783)
    at d (/var/task/app.js:16:7337)
    at new p (/var/task/app.js:174:152577)
    at Function.p.fromSeedBuffer (/var/task/app.js:174:153194)
    at e.fromSeed (/var/task/app.js:78:115784)
    at Function.generateWallet (/var/task/app.js:174:133090)
  message: 'Expected property "0" of type ECPair, got y',
  __label: undefined,
  __property: 0,
  __type: { [Function: t] toJSON: [Function] },
  __value:
   y {
     d:
      n {
        '0': 2098983,
        '1': 21287833,
        '2': 11768436,
        '3': 54383833,
        '4': 65652479,
        '5': 44918812,
        '6': 54939147,
        '7': 1860126,
        '8': 31443095,
        '9': 1243377,
        t: 10,
        s: 0 },
     compressed: true,
     network:
      { hashGenesisBlock:
         '000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f',
        port: 8333,
        portRpc: 8332,
        protocol: [Object],
        seedsDns: [Array],
        versions: [Object],
        name: 'BitcoinCash',
        per1: 100000000,
        unit: 'BCH',
        testnet: false,
        toBitcoinJS: [Function: bound s],
        toBitcore: [Function: bound c],
        messagePrefix: '\u0018BitcoinCash Signed Message:\n',
        bip32: [Object],
        pubKeyHash: 0,
        scriptHash: 5,
        wif: 128,
        dustThreshold: null } },
  __valueTypeName: 'y' }```

**Comment by christroutner** [comment]
I'm more of a back end dev, and don't have much experience with Webpack. Is this something you could submit a PR for? That way we could fix this issue for everyone.

**Comment by tatumio** [comment]
According to this comment in original bitcoinjs-lib repo, this should fix the problem for webpack users.
https://github.com/bitcoinjs/bitcoinjs-lib/issues/959#issuecomment-351040758
