### ISSUE TITLE
Not able to install with Node js LTS (12.18.1)

### ISSUE THREAD

**Issue by jeansouza** [Bitcoin-com/bitbox-sdk#185]
I'm trying to install the lib in a project that uses the current Node js LTS version (12.18.1), but I'm having the following error:

```
make: *** [keccak.target.mk:129: Release/obj.target/keccak/src/addon.o] Error 1
make: Leaving directory '/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-37-generic
gyp ERR! command "/.nvm/versions/node/v12.18.1/bin/node" "/.nvm/versions/node/v12.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/keccak
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-06-25T13_01_59_862Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.
```

Are there any plans to support the current LTS Node js version?

**Comment by christroutner** [comment]
I'm not sure what the plans are for BITBOX, but I maintain a fork of BITBOX called [bch-js](https://github.com/christroutner/bch-js). It uses FullStack.cash instead of rest.bitcoin.com as a back end.

**Comment by mariusk** [comment]
Same with Node v12.18.3.

The exact errors I'm getting are from building `keccak` (five similar in total, different places in the source though):
```
../src/addon.cc:37:47: error: too few arguments to function call, single argument 'context' was not specified
    unsigned int rate = info[0]->IntegerValue();
```
